### ISSUE TITLE
ハンバーガーメニューが作動しない

### ISSUE THREAD

**Issue by MizutoKadowaki0312** [MizutoKadowaki0312/MizutoKadowaki_website#1]
- [ ] テキストのお手本コードを使って動作を確認
- [ ] 自分で実装する

**Comment by MizutoKadowaki0312** [comment]
以下のように組んだコードで実装可能．

```html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/layout.css">
    <title>Document</title>
</head>

<body>
    <!--
        以下5行がハンバーガーメニューのボタン．
        iタグでハンバーガーメニューの線を表現する．
    -->
    <span class="nav_toggle">
        <i></i>
        <i></i>
        <i></i>
    </span>
    <!--
        以下がハンバーガーメニューのメニューリストになる．
        ボタンのクリックによって表示/非表示が切り替わる部分である．
    -->
    <nav class="nav">
        <ul class="nav_menu_ul">
            <li class="nav_menu_li"><a href="#">TOP</a></li>
            <li class="nav_menu_li"><a href="#">ABOUT</a></li>
            <li class="nav_menu_li"><a href="#">BLOG</a></li>
            <li class="nav_menu_li"><a href="#">CONTACT</a></li>
        </ul>
    </nav>
    <script src="js/jquery.min.js"></script>
    <script src="js/index.js"></script>
</body>

</html>
```

```css
/*
	ボタンクリック前
*/
.nav_toggle {
	display: block;
	position: relative;
	width: 1.75rem;
	height: 1.5rem;
}
.nav_toggle i {
	display: block;
	width: 100%;
	height: 2px;
	background-color: #333;
	position: absolute;
	transition: transform 0.5s, opacity 0.5s;
}

/*
	3本線を定義
*/
.nav_toggle i:nth-child(1) {
	top: 0;
}
.nav_toggle i:nth-child(2) {
	top: 0;
	bottom: 0;
	margin: auto;
}
.nav_toggle i:nth-child(3) {
	bottom: 0;
}

/*
	ボタンクリック後(showがある)
*/
.nav_toggle.show i:nth-child(1) {
	transform: translateY(10px) rotate(-45deg);
}
.nav_toggle.show i:nth-child(2) {
	opacity: 0;
}
.nav_toggle.show i:nth-child(3) {
	transform: translateY(-12px) rotate(45deg);
}

/*
	メニューリスト(クリック前)
*/

.nav {
	position: fixed;
	top: 3rem;
	left: 0;
	right: 0;
	bottom: 0;
	padding: 1rem;
	opacity: 0;
	visibility: hidden;
	transition: opacity 0.5s, visibility 0.5s;
}

/*
	メニューリスト(クリック後)
*/
.nav.show {
	opacity: 1;
	visibility: visible;
}
```

```javascript
$(".nav_toggle").on("click", function () {
	$(".nav_toggle, .nav").toggleClass("show");
});

/*
	.vav-toggle をクリックすると後続の{}の記述が実行される．
	(".nav_toggle")は3本線の親要素のクラス名を記述する．

	{}内はボタンをクリックしたことで変化させたい要素のクラス名を表示する．
	.nav-toggle(ボタン) → クリックで3本線を変化させる．
	.nav(メニューリスト) → 表示/非表示の切り替え
	→ これら2つにshowクラスを付与する(css参照)
*/
```
